
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class FootballBook extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public FootballBook() {
        initComponents();
        String sql = String.format("SELECT id,Name,Phone,Date,Time FROM schedule WHERE sport='%s' AND court = '%s'","Football","1");
        setTable(sql,jTable1);
        String sql2 = String.format("SELECT id,Name,Phone,Date,Time FROM schedule WHERE sport='%s' AND court = '%s'","Football","2");
        setTable(sql2,court2table);
        String sql3 = String.format("SELECT id,Name,Phone,Date,Time FROM schedule WHERE sport='%s' AND court = '%s'","Football","3");
        setTable(sql3,court3table);
        String sql4 = String.format("SELECT id,Name,Phone,Date,Time FROM schedule WHERE sport='%s' AND court = '%s'","Football","4");
        setTable(sql4,court4table);
    }

    public void setTable(String sql,JTable table){
        String[] colname = {"Id","Name","Phone no.","Date","Time"};
        DefaultTableModel model = new DefaultTableModel(colname,0);
        
        try{
            DBConnect db = new DBConnect();
            ResultSet rs = db.getConnect(sql);
            
        
            while(rs.next()){
                String Id = rs.getString("Id");
                String name = rs.getString("Name");
                String Phone = rs.getString("Phone");
                String date = rs.getString("Date");
                String time = rs.getString("Time");
                
                String[] row = {Id,name,Phone,date,time};
               
                model.addRow(row);
                
            }
            
        }catch (Exception e){
            e.printStackTrace();
        }
        table.setModel(model);
    }
   
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt2 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        Court4Pane = new javax.swing.JPanel();
        court4date = new com.github.lgooddatepicker.components.DatePicker();
        addBt3 = new javax.swing.JButton();
        court4time = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        court4id = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        court4table = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        Court2Pane = new javax.swing.JPanel();
        court2date = new com.github.lgooddatepicker.components.DatePicker();
        addBt4 = new javax.swing.JButton();
        court2time = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        court2id = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        court2table = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        Court1Pane = new javax.swing.JPanel();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        addBt = new javax.swing.JButton();
        timebox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        idbox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        Court3Pane = new javax.swing.JPanel();
        court3date = new com.github.lgooddatepicker.components.DatePicker();
        addBt2 = new javax.swing.JButton();
        court3time = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        court3id = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        court3table = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AU FITNESS");
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(252, 48, 29));
        jPanel1.setMaximumSize(new java.awt.Dimension(200, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 768));

        bt2.setText("Court 2");
        bt2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        bt1.setText("Court 4");
        bt1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        bt3.setText("Court 1");
        bt3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bt4.setText("Court 3");
        bt4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/football.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt2, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt3, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(bt1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(bt4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(79, 79, 79)
                .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 768));

        jPanel4.setBackground(new java.awt.Color(252, 48, 29));

        jLabel1.setText("Football");
        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel1)
                .addContainerGap(454, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 830, 170));

        court4date.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                court4dateVetoableChange(evt);
            }
        });

        addBt3.setText("Add");
        addBt3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        addBt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBt3ActionPerformed(evt);
            }
        });

        court4time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "15:30-16:00", "16:00-16:30", "16:30-17:00", "17:00:17:30", "17:30:18:00", "18:00-18:30", "18:30-19:00", "19:00-19:30", "19:30-20:00" }));

        jLabel15.setText("Pick the date");
        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel16.setText("Id");
        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel17.setText("Time");
        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jButton5.setText("Delete");
        jButton5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        court4table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Phone no.", "Date", "Time"
            }
        ));
        court4table.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jScrollPane4.setViewportView(court4table);

        jLabel18.setText("Court 4 ");
        jLabel18.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        javax.swing.GroupLayout Court4PaneLayout = new javax.swing.GroupLayout(Court4Pane);
        Court4Pane.setLayout(Court4PaneLayout);
        Court4PaneLayout.setHorizontalGroup(
            Court4PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Court4PaneLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(Court4PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Court4PaneLayout.createSequentialGroup()
                        .addGroup(Court4PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(court4date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Court4PaneLayout.createSequentialGroup()
                                .addComponent(addBt3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(court4time, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(Court4PaneLayout.createSequentialGroup()
                        .addGroup(Court4PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(court4id, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238))))
        );
        Court4PaneLayout.setVerticalGroup(
            Court4PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Court4PaneLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(Court4PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Court4PaneLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(court4id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(Court4PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Court4PaneLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(court4date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(court4time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(Court4PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBt3)
                            .addComponent(jButton5)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("tab2", Court4Pane);

        court2date.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                court2dateVetoableChange(evt);
            }
        });

        addBt4.setText("Add");
        addBt4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        addBt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBt4ActionPerformed(evt);
            }
        });

        court2time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "15:30-16:00", "16:00-16:30", "16:30-17:00", "17:00:17:30", "17:30:18:00", "18:00-18:30", "18:30-19:00", "19:00-19:30", "19:30-20:00" }));

        jLabel19.setText("Pick the date");
        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel20.setText("Id");
        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel21.setText("Time");
        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jButton6.setText("Delete");
        jButton6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        court2table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Phone no.", "Date", "Time"
            }
        ));
        court2table.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jScrollPane5.setViewportView(court2table);

        jLabel22.setText("Court 2 ");
        jLabel22.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        javax.swing.GroupLayout Court2PaneLayout = new javax.swing.GroupLayout(Court2Pane);
        Court2Pane.setLayout(Court2PaneLayout);
        Court2PaneLayout.setHorizontalGroup(
            Court2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Court2PaneLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(Court2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Court2PaneLayout.createSequentialGroup()
                        .addGroup(Court2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(court2date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Court2PaneLayout.createSequentialGroup()
                                .addComponent(addBt4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(court2time, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(Court2PaneLayout.createSequentialGroup()
                        .addGroup(Court2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(court2id, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238))))
        );
        Court2PaneLayout.setVerticalGroup(
            Court2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Court2PaneLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(Court2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Court2PaneLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(court2id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(Court2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Court2PaneLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(court2date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(court2time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(Court2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBt4)
                            .addComponent(jButton6)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("tab3", Court2Pane);

        datePicker1.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                datePicker1VetoableChange(evt);
            }
        });

        addBt.setText("Add");
        addBt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        addBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtActionPerformed(evt);
            }
        });

        timebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "15:30-16:00", "16:00-16:30", "16:30-17:00", "17:00:17:30", "17:30:18:00", "18:00-18:30", "18:30-19:00", "19:00-19:30", "19:30-20:00" }));

        jLabel2.setText("Pick the date");
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel5.setText("Id");
        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel6.setText("Time");
        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jButton2.setText("Delete");
        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Phone no.", "Date", "Time"
            }
        ));
        jTable1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        jLabel10.setText("Court 1 ");
        jLabel10.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        javax.swing.GroupLayout Court1PaneLayout = new javax.swing.GroupLayout(Court1Pane);
        Court1Pane.setLayout(Court1PaneLayout);
        Court1PaneLayout.setHorizontalGroup(
            Court1PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Court1PaneLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(Court1PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Court1PaneLayout.createSequentialGroup()
                        .addGroup(Court1PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Court1PaneLayout.createSequentialGroup()
                                .addComponent(addBt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(timebox, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(Court1PaneLayout.createSequentialGroup()
                        .addGroup(Court1PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idbox, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238))))
        );
        Court1PaneLayout.setVerticalGroup(
            Court1PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Court1PaneLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(Court1PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Court1PaneLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(idbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(Court1PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Court1PaneLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(timebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(Court1PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBt)
                            .addComponent(jButton2)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("tab1", Court1Pane);

        court3date.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                court3dateVetoableChange(evt);
            }
        });

        addBt2.setText("Add");
        addBt2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        addBt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBt2ActionPerformed(evt);
            }
        });

        court3time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "15:30-16:00", "16:00-16:30", "16:30-17:00", "17:00:17:30", "17:30:18:00", "18:00-18:30", "18:30-19:00", "19:00-19:30", "19:30-20:00" }));

        jLabel11.setText("Pick the date");
        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel12.setText("Id");
        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel13.setText("Time");
        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jButton4.setText("Delete");
        jButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        court3table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Phone no.", "Date", "Time"
            }
        ));
        court3table.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jScrollPane3.setViewportView(court3table);

        jLabel14.setText("Court 3 ");
        jLabel14.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        javax.swing.GroupLayout Court3PaneLayout = new javax.swing.GroupLayout(Court3Pane);
        Court3Pane.setLayout(Court3PaneLayout);
        Court3PaneLayout.setHorizontalGroup(
            Court3PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Court3PaneLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(Court3PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Court3PaneLayout.createSequentialGroup()
                        .addGroup(Court3PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(court3date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Court3PaneLayout.createSequentialGroup()
                                .addComponent(addBt2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(court3time, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(Court3PaneLayout.createSequentialGroup()
                        .addGroup(Court3PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(court3id, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238))))
        );
        Court3PaneLayout.setVerticalGroup(
            Court3PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Court3PaneLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(Court3PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Court3PaneLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(court3id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(Court3PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Court3PaneLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(court3date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(court3time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(Court3PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBt2)
                            .addComponent(jButton4)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("tab4", Court3Pane);

        getContentPane().add(jTabbedPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 830, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane5.setSelectedIndex(1);
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane5.setSelectedIndex(0);
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane5.setSelectedIndex(2);
        
        
    }//GEN-LAST:event_bt3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Close.close(this);
        SportsPanel sp = new SportsPanel();
        sp.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane5.setSelectedIndex(3);
    }//GEN-LAST:event_bt4ActionPerformed

    private void addBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtActionPerformed
        // TODO add your handling code here:
        LocalDate date = datePicker1.getDate();
        DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String formattedDate = date.format(dateTimeFormatter);
        String time = timebox.getItemAt(timebox.getSelectedIndex());
        String id = idbox.getText();
        String name = "";
        String phone = "";
        String sport = "Football";
        String court = "1";
        
        try{

            DBConnect db = new DBConnect();
            String sql = String.format("SELECT Name,Phone FROM users WHERE id='%s'",id);
            ResultSet rs = db.getConnect(sql);
            
            if(rs.next()){
                name = rs.getString("Name");
                phone = rs.getString("Phone");

            }
            
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
        List<String> times = new ArrayList();
        
   
        try{

            DBConnect db = new DBConnect();
            String sql = String.format("SELECT Time FROM schedule WHERE date = '%s' AND sport = '%s' AND court = '%s'",date,sport,court);
            ResultSet rs = db.getConnect(sql);
            
            while(rs.next()){
                String t_time = rs.getString("Time");
                times.add(t_time);
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
        
        
            if (times.contains(time)){
                JOptionPane.showMessageDialog(null,"Time not available!","Error",JOptionPane.WARNING_MESSAGE);
            }
            else{
                try{
            DBConnect db =new DBConnect();
            String sql = String.format("INSERT INTO schedule(Id,Name,Phone,sport,court,Date,Time) VALUES('%s','%s','%s','%s','%s','%s','%s') ",id,name,phone,sport,court,date,time);
            db.getUpdate(sql);
            
            
            db.disconnect();
            
            JOptionPane.showMessageDialog(null,"Reserved!");
                }catch(Exception ex){
            
                }
        
            }
        
        String sql = String.format("SELECT id,Name,Phone,Date,Time FROM schedule WHERE sport='%s' AND court = '%s'","Football","1");
        setTable(sql,jTable1);
        
        
               
    }//GEN-LAST:event_addBtActionPerformed

    private void datePicker1VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_datePicker1VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_datePicker1VetoableChange

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String id = idbox.getText();
        
        int a = JOptionPane.showConfirmDialog(null,"Do you really want to delete this Id '?", "Select",JOptionPane.YES_NO_OPTION);
            if(a == 0){
                try{
                    DBConnect db =new DBConnect();
                    String sql = String.format("DELETE FROM schedule WHERE id='%s' AND sport = '%s' AND court = '%s' ",id,"Football","1");
                    db.getUpdate(sql);
                    db.disconnect();

                    JOptionPane.showMessageDialog(null,"Delete Successfully!");
                }catch(Exception ex){
                    ex.printStackTrace();
                }
            }
            String sql = String.format("SELECT id,Name,Phone,Date,Time FROM schedule WHERE sport='%s' AND court = '%s'","Football","1");
            setTable(sql,jTable1);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void court3dateVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_court3dateVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_court3dateVetoableChange

    private void addBt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBt2ActionPerformed
        // TODO add your handling code here:
        LocalDate date = court3date.getDate();
        DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String formattedDate = date.format(dateTimeFormatter);
        String time = court3time.getItemAt(court3time.getSelectedIndex());
        String id = court3id.getText();
        String name = "";
        String phone = "";
        String sport = "Football";
        String court = "3";
        
        try{

            DBConnect db = new DBConnect();
            String sql = String.format("SELECT Name,Phone FROM users WHERE id='%s'",id);
            ResultSet rs = db.getConnect(sql);
            
            if(rs.next()){
                name = rs.getString("Name");
                phone = rs.getString("Phone");

            }
            
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
        List<String> times = new ArrayList();
        
   
        try{

            DBConnect db = new DBConnect();
            String sql = String.format("SELECT Time FROM schedule WHERE date = '%s' AND sport = '%s' AND court = '%s'",date,sport,court);
            ResultSet rs = db.getConnect(sql);
            
            while(rs.next()){
                String t_time = rs.getString("Time");
                times.add(t_time);
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
        
        
            if (times.contains(time)){
                JOptionPane.showMessageDialog(null,"Time not available!","Error",JOptionPane.WARNING_MESSAGE);
            }
            else{
                try{
            DBConnect db =new DBConnect();
            String sql = String.format("INSERT INTO schedule(Id,Name,Phone,sport,court,Date,Time) VALUES('%s','%s','%s','%s','%s','%s','%s') ",id,name,phone,sport,court,date,time);
            db.getUpdate(sql);
            
            
            db.disconnect();
            
            JOptionPane.showMessageDialog(null,"Reserved!");
                }catch(Exception ex){
            
                }
        
            }
        
        String sql = String.format("SELECT id,Name,Phone,Date,Time FROM schedule WHERE sport='%s' AND court = '%s'","Football","3");
        setTable(sql,court3table);
    }//GEN-LAST:event_addBt2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String id = idbox.getText();
        
        int a = JOptionPane.showConfirmDialog(null,"Do you really want to delete this Id '?", "Select",JOptionPane.YES_NO_OPTION);
            if(a == 0){
                try{
                    DBConnect db =new DBConnect();
                    String sql = String.format("DELETE FROM schedule WHERE id='%s' AND sport = '%s' AND court = '%s' ",id,"Football","3");
                    db.getUpdate(sql);
                    db.disconnect();

                    JOptionPane.showMessageDialog(null,"Delete Successfully!");
                }catch(Exception ex){
                    ex.printStackTrace();
                }
            }
            String sql = String.format("SELECT id,Name,Phone,Date,Time FROM schedule WHERE sport='%s' AND court = '%s'","Football","3");
            setTable(sql,court3table);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void court4dateVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_court4dateVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_court4dateVetoableChange

    private void addBt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBt3ActionPerformed
        // TODO add your handling code here:
        LocalDate date = court4date.getDate();
        DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String formattedDate = date.format(dateTimeFormatter);
        String time = court4time.getItemAt(court4time.getSelectedIndex());
        String id = court4id.getText();
        String name = "";
        String phone = "";
        String sport = "Football";
        String court = "4";
        
        try{

            DBConnect db = new DBConnect();
            String sql = String.format("SELECT Name,Phone FROM users WHERE id='%s'",id);
            ResultSet rs = db.getConnect(sql);
            
            if(rs.next()){
                name = rs.getString("Name");
                phone = rs.getString("Phone");

            }
            
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
        List<String> times = new ArrayList();
        
   
        try{

            DBConnect db = new DBConnect();
            String sql = String.format("SELECT Time FROM schedule WHERE date = '%s' AND sport = '%s' AND court = '%s'",date,sport,court);
            ResultSet rs = db.getConnect(sql);
            
            while(rs.next()){
                String t_time = rs.getString("Time");
                times.add(t_time);
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
        
        
            if (times.contains(time)){
                JOptionPane.showMessageDialog(null,"Time not available!","Error",JOptionPane.WARNING_MESSAGE);
            }
            else{
                try{
            DBConnect db =new DBConnect();
            String sql = String.format("INSERT INTO schedule(Id,Name,Phone,sport,court,Date,Time) VALUES('%s','%s','%s','%s','%s','%s','%s') ",id,name,phone,sport,court,date,time);
            db.getUpdate(sql);
            
            
            db.disconnect();
            
            JOptionPane.showMessageDialog(null,"Reserved!");
                }catch(Exception ex){
            
                }
        
            }
        
        String sql = String.format("SELECT id,Name,Phone,Date,Time FROM schedule WHERE sport='%s' AND court = '%s'","Football","4");
        setTable(sql,court4table);
    }//GEN-LAST:event_addBt3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String id = idbox.getText();
        
        int a = JOptionPane.showConfirmDialog(null,"Do you really want to delete this Id '?", "Select",JOptionPane.YES_NO_OPTION);
            if(a == 0){
                try{
                    DBConnect db =new DBConnect();
                    String sql = String.format("DELETE FROM schedule WHERE id='%s' AND sport = '%s' AND court = '%s' ",id,"Football","4");
                    db.getUpdate(sql);
                    db.disconnect();

                    JOptionPane.showMessageDialog(null,"Delete Successfully!");
                }catch(Exception ex){
                    ex.printStackTrace();
                }
            }
            String sql = String.format("SELECT id,Name,Phone,Date,Time FROM schedule WHERE sport='%s' AND court = '%s'","Football","4");
            setTable(sql,court4table);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void court2dateVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_court2dateVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_court2dateVetoableChange

    private void addBt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBt4ActionPerformed
        // TODO add your handling code here:
        LocalDate date = court2date.getDate();
        DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String formattedDate = date.format(dateTimeFormatter);
        String time = court2time.getItemAt(court2time.getSelectedIndex());
        String id = court2id.getText();
        String name = "";
        String phone = "";
        String sport = "Football";
        String court = "2";
        
        try{

            DBConnect db = new DBConnect();
            String sql = String.format("SELECT Name,Phone FROM users WHERE id='%s'",id);
            ResultSet rs = db.getConnect(sql);
            
            if(rs.next()){
                name = rs.getString("Name");
                phone = rs.getString("Phone");

            }
            
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
        List<String> times = new ArrayList();
        
   
        try{

            DBConnect db = new DBConnect();
            String sql = String.format("SELECT Time FROM schedule WHERE date = '%s' AND sport = '%s' AND court = '%s'",date,sport,court);
            ResultSet rs = db.getConnect(sql);
            
            while(rs.next()){
                String t_time = rs.getString("Time");
                times.add(t_time);
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
        
        
            if (times.contains(time)){
                JOptionPane.showMessageDialog(null,"Time not available!","Error",JOptionPane.WARNING_MESSAGE);
            }
            else{
                try{
            DBConnect db =new DBConnect();
            String sql = String.format("INSERT INTO schedule(Id,Name,Phone,sport,court,Date,Time) VALUES('%s','%s','%s','%s','%s','%s','%s') ",id,name,phone,sport,court,date,time);
            db.getUpdate(sql);
            
            
            db.disconnect();
            
            JOptionPane.showMessageDialog(null,"Reserved!");
                }catch(Exception ex){
            
                }
        
            }
        
        String sql = String.format("SELECT id,Name,Phone,Date,Time FROM schedule WHERE sport='%s' AND court = '%s'","Football","2");
        setTable(sql,court2table);
    }//GEN-LAST:event_addBt4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String id = idbox.getText();
        
        int a = JOptionPane.showConfirmDialog(null,"Do you really want to delete this Id '?", "Select",JOptionPane.YES_NO_OPTION);
            if(a == 0){
                try{
                    DBConnect db =new DBConnect();
                    String sql = String.format("DELETE FROM schedule WHERE id='%s' AND sport = '%s' AND court = '%s' ",id,"Football","2");
                    db.getUpdate(sql);
                    db.disconnect();

                    JOptionPane.showMessageDialog(null,"Delete Successfully!");
                }catch(Exception ex){
                    ex.printStackTrace();
                }
            }
            String sql = String.format("SELECT id,Name,Phone,Date,Time FROM schedule WHERE sport='%s' AND court = '%s'","Football","2");
            setTable(sql,court2table);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TennisBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TennisBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TennisBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TennisBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FootballBook().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Court1Pane;
    private javax.swing.JPanel Court2Pane;
    private javax.swing.JPanel Court3Pane;
    private javax.swing.JPanel Court4Pane;
    private javax.swing.JButton addBt;
    private javax.swing.JButton addBt2;
    private javax.swing.JButton addBt3;
    private javax.swing.JButton addBt4;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private com.github.lgooddatepicker.components.DatePicker court2date;
    private javax.swing.JTextField court2id;
    private javax.swing.JTable court2table;
    private javax.swing.JComboBox<String> court2time;
    private com.github.lgooddatepicker.components.DatePicker court3date;
    private javax.swing.JTextField court3id;
    private javax.swing.JTable court3table;
    private javax.swing.JComboBox<String> court3time;
    private com.github.lgooddatepicker.components.DatePicker court4date;
    private javax.swing.JTextField court4id;
    private javax.swing.JTable court4table;
    private javax.swing.JComboBox<String> court4time;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.JTextField idbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> timebox;
    // End of variables declaration//GEN-END:variables
}
