
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class SportsPanel extends javax.swing.JFrame {

    /**
     * Creates new form MenuPanel
     */
    public SportsPanel() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tennisB = new javax.swing.JButton();
        badmintonB = new javax.swing.JButton();
        basketB = new javax.swing.JButton();
        footB = new javax.swing.JButton();
        tableTB = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        gymB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AU FITNESS");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(194, 202, 215));

        tennisB.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        tennisB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tn.png"))); // NOI18N
        tennisB.setBorder(null);
        tennisB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tennisBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tennisBMouseExited(evt);
            }
        });
        tennisB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tennisBActionPerformed(evt);
            }
        });

        badmintonB.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        badmintonB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bmd.png"))); // NOI18N
        badmintonB.setBorder(null);
        badmintonB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                badmintonBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                badmintonBMouseExited(evt);
            }
        });
        badmintonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badmintonBActionPerformed(evt);
            }
        });

        basketB.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        basketB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bkb.png"))); // NOI18N
        basketB.setBorder(null);
        basketB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                basketBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                basketBMouseExited(evt);
            }
        });
        basketB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basketBActionPerformed(evt);
            }
        });

        footB.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        footB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fb.png"))); // NOI18N
        footB.setBorder(null);
        footB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                footBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                footBMouseExited(evt);
            }
        });
        footB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                footBActionPerformed(evt);
            }
        });

        tableTB.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        tableTB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tbt.png"))); // NOI18N
        tableTB.setBorder(null);
        tableTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tableTBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tableTBMouseExited(evt);
            }
        });
        tableTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableTBActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(252, 48, 29));

        jLabel1.setText("Booking");
        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(252, 48, 29));

        jButton6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(718, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        gymB.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        gymB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gym.png"))); // NOI18N
        gymB.setBorder(null);
        gymB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gymBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gymBMouseExited(evt);
            }
        });
        gymB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gymBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(tennisB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(badmintonB, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addComponent(tableTB)
                .addGap(78, 78, 78))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(basketB, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gymB, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(footB, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(badmintonB, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(gymB, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tableTB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(footB, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tennisB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(basketB, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(67, 67, 67)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tennisBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tennisBActionPerformed
        // TODO add your handling code here:
        Close.close(this);
        TennisBook tb = new TennisBook();
        tb.setVisible(true);
            
    }//GEN-LAST:event_tennisBActionPerformed

    private void badmintonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badmintonBActionPerformed
        // TODO add your handling code here:
        Close.close(this);
        BadmintonBook bb = new BadmintonBook();
        bb.setVisible(true);
       
    }//GEN-LAST:event_badmintonBActionPerformed

    private void basketBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basketBActionPerformed
        // TODO add your handling code here:
        Close.close(this);
        BasketballBook bkb = new BasketballBook();
        bkb.setVisible(true);
    }//GEN-LAST:event_basketBActionPerformed

    private void footBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_footBActionPerformed
        // TODO add your handling code here:
        Close.close(this);
        FootballBook fb = new FootballBook();
        fb.setVisible(true);
    }//GEN-LAST:event_footBActionPerformed

    private void tableTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableTBActionPerformed
        // TODO add your handling code here:
        Close.close(this);
        TableTennisBook tbb = new TableTennisBook();
        tbb.setVisible(true);
        
               
    }//GEN-LAST:event_tableTBActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
      
            Close.close(this);
            MenuPanel mp = new MenuPanel();
            mp.setVisible(true);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void gymBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gymBActionPerformed
        // TODO add your handling code here:
        Close.close(this);
        GymBook gb = new GymBook();
        gb.setVisible(true);
                
    }//GEN-LAST:event_gymBActionPerformed

    private void tennisBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tennisBMouseEntered
        // TODO add your handling code here:
        
        tennisB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tnhv.png")));
    }//GEN-LAST:event_tennisBMouseEntered

    private void tennisBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tennisBMouseExited
        // TODO add your handling code here:
        
        tennisB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tn.png")));
    }//GEN-LAST:event_tennisBMouseExited

    private void badmintonBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_badmintonBMouseEntered
        // TODO add your handling code here:
        
        badmintonB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bmdhv.png")));
    }//GEN-LAST:event_badmintonBMouseEntered

    private void badmintonBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_badmintonBMouseExited
        // TODO add your handling code here:
        
        badmintonB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bmd.png")));
    }//GEN-LAST:event_badmintonBMouseExited

    private void tableTBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTBMouseEntered
        // TODO add your handling code here:
        
        tableTB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tbthv.png")));
    }//GEN-LAST:event_tableTBMouseEntered

    private void tableTBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTBMouseExited
        // TODO add your handling code here:
        
        tableTB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tbt.png")));
    }//GEN-LAST:event_tableTBMouseExited

    private void basketBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basketBMouseEntered
        // TODO add your handling code here:
        
        basketB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bkbhv.png")));
    }//GEN-LAST:event_basketBMouseEntered

    private void basketBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basketBMouseExited
        // TODO add your handling code here:
        
        basketB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bkb.png")));
    }//GEN-LAST:event_basketBMouseExited

    private void footBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_footBMouseEntered
        // TODO add your handling code here:
        
        footB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fbhv.png")));
    }//GEN-LAST:event_footBMouseEntered

    private void footBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_footBMouseExited
        // TODO add your handling code here:
        
        footB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fb.png")));
    }//GEN-LAST:event_footBMouseExited

    private void gymBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gymBMouseEntered
        // TODO add your handling code here:
        
        gymB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gymhv.png")));
    }//GEN-LAST:event_gymBMouseEntered

    private void gymBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gymBMouseExited
        // TODO add your handling code here:
        
        gymB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gym.png")));
    }//GEN-LAST:event_gymBMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SportsPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton badmintonB;
    private javax.swing.JButton basketB;
    private javax.swing.JButton footB;
    private javax.swing.JButton gymB;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton tableTB;
    private javax.swing.JButton tennisB;
    // End of variables declaration//GEN-END:variables
}
